# Generated by Django 3.2.7 on 2021-10-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default='hzhpdt1xrdhbatsp2i2qjto9ilv4x081vq8bomt7yn99oilwluurminxjlpenarv', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
