# Generated by Django 3.2.7 on 2021-10-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default='zrc1kwl9556ffbta54lutuwvbn9c6puzmnihhbzqylpdgdaquoqpw9gzv1ozhqnq', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
