# Generated by Django 3.2.7 on 2021-11-11 11:14

import comptes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='date_de_retret',
        ),
        migrations.AlterField(
            model_name='demande',
            name='Scan_cerificat_de_inscription',
            field=models.ImageField(blank=True, upload_to=comptes.models.custom_doc),
        ),
        migrations.AlterField(
            model_name='demande',
            name='Scan_cerificat_de_reussite',
            field=models.ImageField(blank=True, upload_to=comptes.models.custom_doc),
        ),
        migrations.AlterField(
            model_name='demande',
            name='lieu_de_retret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='demande',
            name='type',
            field=models.CharField(blank=True, choices=[('Demende de diplome', 'Demende de diplome'), ("Demende d'attestation de passage", "Demende d'attestation de passage"), ('Demende de Certificat de reussite', 'Demende de Certificat de reussite'), ('Demende de diplicata de releve de note', 'Demende de diplicata de releve de note'), ("Demende de carte d'etudiant", "Demende de carte d'etudiant"), ("Demende de certificat d'inscription", "Demende de certificat d'inscription")], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default='u8twsrq8y3apifxgfs1k1w6w7cphf0ebfxlpqpx1b2yi7vmn101etfdkk564snup', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
