# Generated by Django 3.2.7 on 2021-11-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_auto_20211111_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default='ay9dadbrshujjir2j59zoqj1drueytzeokqs5l6dwxdpvkbdzuvjxzackj1gqdre', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
