# Generated by Django 3.2.7 on 2021-11-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='departement',
            field=models.CharField(choices=[], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='formation',
            field=models.CharField(choices=[], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default='wcky3k4xzvybykakyhdffayfpmswj1mejk34mgoqkw5lryyktrk0vqambtq8ask4', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pays_de_naissacne',
            field=models.CharField(choices=[], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pays_de_residence',
            field=models.CharField(choices=[], max_length=255),
        ),
    ]
