# Generated by Django 3.2.7 on 2021-11-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_auto_20211111_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default='yo1hlsreuoxp6xoj5pnn4znq9kmowfh7t32maqdg9ifxcd8vxczr2tmkvyeplzt3', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
